docs(dtfs2-none): update readme
foundry4/dtfs2 pull request #3147
Opened 2024-05-23 08:12 UTC by natdeanlewissoftwire

## Introduction :pencil2:
These are some documentation updates that I discovered need to be made during my rampup

## Resolution :heavy_check_mark:

Add a step for the `npm run env:copy` command that's been added recently
Fix the routing for login credentials files

## Miscellaneous :heavy_plus_sign:
Add a touch more detail to other steps to clarify a few phrasings etc.

2024-05-23 08:48 UTC, AlexBramhill approved these changes

2024-05-23 13:43 UTC, abhi-markan requested changes
One minor comment to address please.

2024-05-24 09:15 UTC, natdeanlewissoftwire commented on README.md
> +8. Run `npm install` in the root folder of the repository. (note: this will install dependencies for the entire project, including those specified in sub-packages. More details on this in the [npm wo
It most certainly can :)

2024-06-03 08:28 UTC, abhi-markan approved these changes

2024-06-04 07:29 UTC, merged