DTFS2-4783 - update BSS/EWCS data migration mappings. Remove old workflow/type-b files
foundry4/dtfs2 pull request #715
Opened 2022-02-17 17:19 UTC by ttbarnes

## Summary
- When "import deal into our deals collection" is called, add each facility to the facilities collection.
- Update deal and facility property mappings to match the data model
  - Create `map-deal-root` for all top level properties, move and update mappings
  - Add mapping for `exporter.companyName`
  - Remove usage of existing portal _id as the main deal/facility _id (keeping a reference to it under `dataMigrationInfo.v1_ID`). Use new mongo ID instead.
  - Add facility types (bond/cash etc)

## Other things
- Update mandatory criteria import
- Add extra logs
- Add `npm install typescript` to reference-data Dockerfile
- Remove unused type-b integration functions/mappings
- Move k2-mappings into data-migration directory

2022-02-24 18:00 UTC, IgnatG approved these changes

2022-02-25 12:07 UTC, abhi-markan requested changes
Failing test.

2022-03-01 17:12 UTC, abhi-markan approved these changes
`log.addError` where does that saves the data?

2022-03-01 17:24 UTC, IgnatG approved these changes

2022-03-01 17:24 UTC, merged